import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav/Nav";


const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ['400', '600', '800'],
});

export const metadata: Metadata = {
  title: "ProodeClon",
  description: "Generated by Matias Ramos",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} pt-navHeight`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
